f = open(r"C:\Users\Neeraj\Desktop\Python\file.txt")
print(f.name)
print(f"cursor position : {f.tell()}")
print(f.readline(), end = "")
print("before seek method")
print(f"cursor position : {f.tell()}")
f.seek(0)
print("after seek method")
print(f"cursor position : {f.tell()}")
print(f.read())
f.seek(0)
print(f"cursor position : {f.tell()}")
lines = f.readlines()
print(lines)
print(f"list length = {len(lines)}")
for line in lines:
    print(line, end = "")
print("\n")
print(f.closed)
f.close()
print(f.closed)